sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t orel555/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true orel555/docker-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-north-1"
#   app: "frontend"
#   env: "Frontend-env"
#   bucket_name: "elasticbeanstalk-eu-north-1-585768158683"
#   bucket_path: "frontend"
#   on:
#     branch: main
